[package]
name = "cmx-utils"
version = "0.1.0"
edition = "2024"

[dependencies]
    dotenvy = "0.15"
    jsonwebtoken = { version = "10" }
    tracing-subscriber = { version = "0.3", features = ["env-filter"] }
    tracing = "0.1"  